# Generated by Django 5.2.11 on 2026-09-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_masterresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tailored_resume_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterresume',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
